/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author danmanfer2
 */
public class AveriasView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AveriasView.class.getName());

    /**
     * Creates new form AveriasView
     */
    public AveriasView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDescInic = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtProcRealizado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMaquinariaID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTipoAveriaID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtOperarioID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTecnicoID = new javax.swing.JTextField();
        txtFechaInicio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFechaAsig = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtFechaAcep = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtFechaFin = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnReportar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Descripción Averia:");

        jLabel2.setText("Procedimiento Realizado:");

        jLabel3.setText("ID Máquina:");

        jLabel4.setText("ID Tipo Avería:");

        jLabel5.setText("ID Operario:");

        jLabel6.setText("ID Técnico Asignado:");

        jLabel7.setText("Fecha Inicio:");

        jLabel8.setText("Fecha Asignación:");

        jLabel9.setText("Fecha Aceptación:");

        jLabel10.setText("Fecha Finalización:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Máquina", "Tipo", "Operario", "Técnico", "Fecha Inicio"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnReportar.setText("Reportar Avería");

        btnLimpiar.setText("Limpiar");

        btnActualizar.setText("Actualizar");

        btnEliminar.setText("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFechaAcep, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(txtDescInic)
                        .addComponent(txtProcRealizado)
                        .addComponent(txtMaquinariaID)
                        .addComponent(txtTipoAveriaID)
                        .addComponent(txtOperarioID)
                        .addComponent(txtTecnicoID)
                        .addComponent(txtFechaAsig, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtFechaFin)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnReportar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualizar)
                        .addGap(34, 34, 34)
                        .addComponent(btnEliminar)
                        .addGap(35, 35, 35)
                        .addComponent(btnLimpiar)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtDescInic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtProcRealizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMaquinariaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTipoAveriaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtOperarioID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtTecnicoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtFechaAsig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtFechaAcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReportar)
                            .addComponent(btnLimpiar)
                            .addComponent(btnActualizar)
                            .addComponent(btnEliminar))
                        .addGap(22, 22, 22))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AveriasView().setVisible(true));
    }
    
    public String getDescInic() { return txtDescInic.getText().trim(); }
    public String getProcRealizado() { return txtProcRealizado.getText().trim(); }
    
    public String getMaquinariaID() { return txtMaquinariaID.getText().trim(); }
    public String getTipoAveriaID() { return txtTipoAveriaID.getText().trim(); }
    public String getOperarioID() { return txtOperarioID.getText().trim(); }
    public String getTecnicoID() { return txtTecnicoID.getText().trim(); }

    public String getFechaInicio() { return txtFechaInicio.getText().trim(); }
    public String getFechaAsig() { return txtFechaAsig.getText().trim(); }
    public String getFechaAcep() { return txtFechaAcep.getText().trim(); }
    public String getFechaFin() { return txtFechaFin.getText().trim(); }

    // =======================================================
    // MÉTODOS PARA LA TABLA (Añadidos manualmente)
    // =======================================================

    public void llenarTabla(java.util.List<modelo.Averia> averias) {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0); // Limpiar tabla
        
        for (modelo.Averia a : averias) {
            modelo.addRow(new Object[]{
                a.getCodigoAveria(),
                a.getMaquinariaFK(),
                a.getTipoAveriaFK(),
                a.getUsuarioReportaFK(),
                a.getUsuarioTecnicoFK() > 0 ? a.getUsuarioTecnicoFK() : "Sin asignar",
                a.getFechaInicioAver()
            });
        }
    }

    public int getIdSeleccionado() {
        int fila = jTable1.getSelectedRow();
        if (fila == -1) return -1;
        return (int) jTable1.getValueAt(fila, 0); 
    }

    // =======================================================
    // LISTENERS (Añadidos manualmente)
    // =======================================================
    
    public void setBtnReportarListener(java.awt.event.ActionListener l) { btnReportar.addActionListener(l); }
    public void setBtnActualizarListener(java.awt.event.ActionListener l) { btnActualizar.addActionListener(l); }
    public void setBtnEliminarListener(java.awt.event.ActionListener l) { btnEliminar.addActionListener(l); }
    public void setBtnLimpiarListener(java.awt.event.ActionListener l) { btnLimpiar.addActionListener(l); }

    // =======================================================
    // UTILIDADES (Añadidas manualmente)
    // =======================================================

    public void limpiarFormulario() {
        txtDescInic.setText("");
        txtProcRealizado.setText("");
        txtMaquinariaID.setText("");
        txtTipoAveriaID.setText("");
        txtOperarioID.setText("");
        txtTecnicoID.setText("");
        txtFechaInicio.setText("");
        txtFechaAsig.setText("");
        txtFechaAcep.setText("");
        txtFechaFin.setText("");
        jTable1.clearSelection();
    }

    public void mostrarMensaje(String msg) {
        javax.swing.JOptionPane.showMessageDialog(this, msg);
    }

    public void mostrarError(String msg) {
        javax.swing.JOptionPane.showMessageDialog(this, msg, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnReportar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDescInic;
    private javax.swing.JTextField txtFechaAcep;
    private javax.swing.JTextField txtFechaAsig;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtMaquinariaID;
    private javax.swing.JTextField txtOperarioID;
    private javax.swing.JTextField txtProcRealizado;
    private javax.swing.JTextField txtTecnicoID;
    private javax.swing.JTextField txtTipoAveriaID;
    // End of variables declaration//GEN-END:variables
}
