/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Util.EstiloUI;
import modelo.Averia;
import modelo.Usuario;

/**
 *
 * @author danmanfer2
 */
public class EditarAveriasView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditarAveriasView.class.getName());

    /**
     * Creates new form AveriasView
     */
    
    private void personalizarVista(){
        Util.EstiloUI.aplicarVentana(this);
        Util.EstiloUI.aplicarTitulo(jLabel1);
        Util.EstiloUI.aplicarTexto(jLabel2);
        Util.EstiloUI.aplicarTexto(jLabel3);
        Util.EstiloUI.aplicarBotonPrimario(btnEditar);
        
        
        
    }
    
    public EditarAveriasView() {
       
        initComponents();
        EstiloUI.aplicarPantallaCompleta(this);
        EstiloUI.aplicarFondo(this, jPanel1);
        personalizarVista();
    }

    private void aplicarEstilos() {
        Util.EstiloUI.aplicarVentana(this);
        Util.EstiloUI.aplicarTabla(jTable1);
        Util.EstiloUI.aplicarPantallaCompleta(this);

        Util.EstiloUI.aplicarBotonPrimario(btnEditar);
        Util.EstiloUI.aplicarBotonPeligro(btnVolver);
    }
    
    public void setDatosAveria(modelo.Averia a) {
        txtDescInic.setText(a.getDescInicAveria());
        txtProcRealizado.setText(a.getProcRealizadoTecnico());
        txtMaquinariaID.setText(String.valueOf(a.getMaquinariaFK()));
        txtTipoAveriaID.setText(String.valueOf(a.getTipoAveriaFK()));
        txtUsuario.setText(String.valueOf(a.getUsuarioReportaFK()));
        txtTecnicoID.setText(a.getUsuarioTecnicoFK() != null ? String.valueOf(a.getUsuarioTecnicoFK()) : "");
        txtFechaInicio.setText(String.valueOf(a.getFechaInicioAver()));
        txtFechaAsig.setText(String.valueOf(a.getFechaAsigTecnico()));
        txtFechaAcep.setText(String.valueOf(a.getFechaAcepTecnico()));
        txtFechaFin.setText(String.valueOf(a.getFechaFinalizTecnico()));
    }
    
    public void setTablaListener(javax.swing.event.ListSelectionListener l) {
        jTable1.getSelectionModel().addListSelectionListener(l);
    }

        public void setBtnVolverListener(java.awt.event.ActionListener l) {
        btnVolver.addActionListener(l);
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtProcRealizado = new javax.swing.JTextField();
        txtFechaAsig = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMaquinariaID = new javax.swing.JTextField();
        txtFechaAcep = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTipoAveriaID = new javax.swing.JTextField();
        txtFechaFin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtTecnicoID = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        txtDescInic = new javax.swing.JTextField();
        txtFechaInicio = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Procedimiento Realizado:");

        jLabel3.setText("ID Máquina:");

        txtMaquinariaID.setEditable(false);

        jLabel4.setText("ID Tipo Avería:");

        txtTipoAveriaID.setEditable(false);

        jLabel5.setText("ID Usuario:");

        txtUsuario.setEnabled(false);

        jLabel6.setText("ID Técnico Asignado:");

        txtTecnicoID.setEnabled(false);

        jLabel7.setText("Fecha Inicio:");

        jLabel3.setText("ID Máquina:");

        jLabel8.setText("Fecha Asignación:");

        txtFechaAcep.setEnabled(false);

        jLabel4.setText("ID Tipo Avería:");

        jLabel9.setText("Fecha Aceptación:");

        txtFechaFin.setEnabled(false);

        jLabel5.setText("ID Usuario:");

        jLabel10.setText("Fecha Finalización:");

        txtUsuario.setEnabled(false);

        jLabel6.setText("ID Técnico Asignado:");

        jLabel1.setText("Descripción Averia:");

        txtTecnicoID.setEnabled(false);

        btnEditar.setText("Guardar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Máquina", "Tipo", "Operario", "Técnico", "F. Inicio", "F. Asignación", "F. Aceptación", "F. Finalización"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(btnVolver))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFechaAcep, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtFechaInicio)
                        .addComponent(txtDescInic)
                        .addComponent(txtProcRealizado)
                        .addComponent(txtMaquinariaID)
                        .addComponent(txtTipoAveriaID)
                        .addComponent(txtUsuario)
                        .addComponent(txtTecnicoID)
                        .addComponent(txtFechaAsig, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtFechaFin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(296, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtDescInic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtProcRealizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMaquinariaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTipoAveriaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtTecnicoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtFechaAsig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtFechaAcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(172, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditarAveriasView().setVisible(true));
    }
    
    public String getDescInic() { return txtDescInic.getText().trim(); }
    public String getProcRealizado() { return txtProcRealizado.getText().trim(); }
    
    public String getMaquinariaID() { return txtMaquinariaID.getText().trim(); }
    public String getTipoAveriaID() { return txtTipoAveriaID.getText().trim(); }
    public String getOperarioID() { return txtUsuario.getText().trim(); }
    public String getTecnicoID() { return txtTecnicoID.getText().trim(); }

    public String getFechaInicio() { return txtFechaInicio.getText().trim(); }
    public String getFechaAsig() { return txtFechaAsig.getText().trim(); }
    public String getFechaAcep() { return txtFechaAcep.getText().trim(); }
    public String getFechaFin() { return txtFechaFin.getText().trim(); }

    // =======================================================
    // MÉTODOS PARA LA TABLA (Añadidos manualmente)
    // =======================================================

    
    public Averia getDatosFormulario() {
        Averia a = new Averia();

        a.setDescInicAveria(getDescInic());
        a.setProcRealizadoTecnico(getProcRealizado());
        a.setMaquinariaFK(Integer.parseInt(getMaquinariaID()));
        a.setTipoAveriaFK(Integer.parseInt(getTipoAveriaID()));
        a.setUsuarioReportaFK(Integer.parseInt(getOperarioID()));

        if (getTecnicoID() != null && !getTecnicoID().isBlank()) {
            a.setUsuarioTecnicoFK(Integer.parseInt(getTecnicoID()));
        } else {
            a.setUsuarioTecnicoFK(null);
        }

        if (getFechaInicio() != null && !getFechaInicio().isBlank() && !"null".equalsIgnoreCase(getFechaInicio())) {
            a.setFechaInicioAver(java.sql.Timestamp.valueOf(getFechaInicio()));
        }

        if (getFechaAsig() != null && !getFechaAsig().isBlank() && !"null".equalsIgnoreCase(getFechaAsig())) {
            a.setFechaAsigTecnico(java.sql.Timestamp.valueOf(getFechaAsig()));
        } else {
            a.setFechaAsigTecnico(null);
        }

        if (getFechaAcep() != null && !getFechaAcep().isBlank() && !"null".equalsIgnoreCase(getFechaAcep())) {
            a.setFechaAcepTecnico(java.sql.Timestamp.valueOf(getFechaAcep()));
        } else {
            a.setFechaAcepTecnico(null);
        }

        if (getFechaFin() != null && !getFechaFin().isBlank() && !"null".equalsIgnoreCase(getFechaFin())) {
            a.setFechaFinalizTecnico(java.sql.Timestamp.valueOf(getFechaFin()));
        } else {
            a.setFechaFinalizTecnico(null);
        }

        return a;
    }
    
    public void llenarTabla(java.util.List<modelo.Averia> averias) {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0); // Limpiar tabla
        
        for (modelo.Averia a : averias) {
            modelo.addRow(new Object[]{
                a.getCodigoAveria(),
                a.getMaquinariaFK(),
                a.getTipoAveriaFK(),
                a.getUsuarioReportaFK(),
                a.getUsuarioTecnicoFK() > 0 ? a.getUsuarioTecnicoFK() : "Sin asignar",
                a.getFechaInicioAver()
            });
        }
    }

    public int getIdSeleccionado() {
        int fila = jTable1.getSelectedRow();
        if (fila == -1) return -1;
        return (int) jTable1.getValueAt(fila, 0); 
    }

    // =======================================================
    // LISTENERS (Añadidos manualmente)
    // =======================================================
    
    public void setBtnActualizarListener(java.awt.event.ActionListener l) { btnEditar.addActionListener(l); }


    // =======================================================
    // UTILIDADES (Añadidas manualmente)
    // =======================================================

    public void limpiarFormulario() {
        txtDescInic.setText("");
        txtProcRealizado.setText("");
        txtMaquinariaID.setText("");
        txtTipoAveriaID.setText("");
        txtUsuario.setText("");
        txtTecnicoID.setText("");
        txtFechaInicio.setText("");
        txtFechaAsig.setText("");
        txtFechaAcep.setText("");
        txtFechaFin.setText("");
        jTable1.clearSelection();
    }

    public void mostrarMensaje(String msg) {
        javax.swing.JOptionPane.showMessageDialog(this, msg);
    }

    public void mostrarError(String msg) {
        javax.swing.JOptionPane.showMessageDialog(this, msg, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDescInic;
    private javax.swing.JTextField txtFechaAcep;
    private javax.swing.JTextField txtFechaAsig;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtMaquinariaID;
    private javax.swing.JTextField txtProcRealizado;
    private javax.swing.JTextField txtTecnicoID;
    private javax.swing.JTextField txtTipoAveriaID;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
