/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Util.EstiloUI;

/**
 *
 * @author danmanfer2
 */
public class UsuariosView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UsuariosView.class.getName());

    /**
     * Creates new form UsuariosView
     */
    public UsuariosView() {
        initComponents();
        setTitle("Gestión de Usuarios");
        EstiloUI.aplicarPantallaCompleta(this);
        EstiloUI.aplicarFondo(this, jPanel1);
        personalizarVista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");

        btnAgregar.setText("Agregar");

        btnVolver.setText("Volver");

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido", "Email", "Rol", "Activo"
            }
        ));
        jScrollPane1.setViewportView(tblUsuarios);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregar)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addGap(18, 18, 18)
                .addComponent(btnEditar)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditar)
                            .addComponent(btnEliminar)
                            .addComponent(btnAgregar))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVolver)
                        .addGap(16, 16, 16))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(308, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(281, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UsuariosView().setVisible(true));
    }
    
  

    

    

    // Convertimos el texto del ROL a número (int). Si falla, devolvemos 0.
  

   

    // =======================================================
    // MÉTODOS PARA MANIPULAR LA TABLA
    // =======================================================

    /**
     * Recibe una lista de usuarios del modelo y rellena la JTable.
     * @param usuarios
     */
    public void llenarTabla(java.util.List<modelo.Usuario> usuarios) {
        // Obtenemos el modelo de la tabla para poder modificar sus filas
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblUsuarios.getModel();
        
        // 1. Limpiamos la tabla primero (para no duplicar datos al refrescar)
        modelo.setRowCount(0);
        
        // 2. Recorremos la lista y agregamos filas una por una
        for (modelo.Usuario u : usuarios) {
            modelo.addRow(new Object[]{
                u.getCodigoUsuario(),
                u.getNombre(),
                u.getApellido(),
                u.getEmail(),
                u.getCodigoRolFK(),
                u.isActivo() ? "Sí" : "No"
            });
        }
    }

    /**
     * Devuelve el ID del usuario seleccionado en la tabla.
     * Retorna -1 si no hay ninguna fila seleccionada.
     * @return 
     */
    public int getIdSeleccionado() {
        int fila = tblUsuarios.getSelectedRow();
        if (fila == -1) {
            return -1;
        }
        // Asumiendo que la columna 0 es el ID (según tu modelo de tabla)
        return (int) tblUsuarios.getValueAt(fila, 0);
    }

    // =======================================================
    // LISTENERS (Conexión con los botones)
    // =======================================================
    
    // Métodos puente para botones
    public void escucharBtnAgregar(java.awt.event.ActionListener l) { 
        btnAgregar.addActionListener(l); 
    }
    
    public void escucharBtnEliminar(java.awt.event.ActionListener l) { 
        btnEliminar.addActionListener(l); 
    }
    
    public void setBtnLimpiarListener(java.awt.event.ActionListener l) {
        btnEditar.addActionListener(l);
    }
    
    public void setBtnVolverListener(java.awt.event.ActionListener listener) {
        btnVolver.addActionListener(listener);
    }
    
    public void escucharEditar(java.awt.event.ActionListener listener){
        btnEditar.addActionListener(listener);
    }

    // =======================================================
    // UTILIDADES
    // =======================================================

    public void limpiarFormulario() {
        
        tblUsuarios.clearSelection();
    }

    public void mostrarMensaje(String msg) {
        javax.swing.JOptionPane.showMessageDialog(this, msg);
    }

    public void mostrarError(String msg) {
        javax.swing.JOptionPane.showMessageDialog(this, msg, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    
    // Método para personalizar la vista
    private void personalizarVista(){
        Util.EstiloUI.aplicarVentana(this);
      
        
        
        Util.EstiloUI.aplicarBotonExito(btnAgregar);
        Util.EstiloUI.aplicarBotonPeligro(btnEliminar);
        Util.EstiloUI.aplicarBotonSecundario(btnEditar);
        
        Util.EstiloUI.aplicarTabla(tblUsuarios);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuarios;
    // End of variables declaration//GEN-END:variables
}
