/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author konatasht
 */
public class VistaAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaAdmin.class.getName());

    /**
     * Creates new form VistaAdmin
     */
    public VistaAdmin() {
        initComponents();
        personalizarVista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        lblBienvenida = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        btnPerfil = new javax.swing.JMenuItem();
        btnSalir = new javax.swing.JMenuItem();
        btnCerrarSesion = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnAveria = new javax.swing.JMenuItem();
        btnUsuario = new javax.swing.JMenuItem();
        btnMaquina = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBienvenida.setText("¡Bienvenido, ...!");

        jMenu3.setText("Sesión");

        btnPerfil.setText("Perfil");
        jMenu3.add(btnPerfil);

        btnSalir.setText("Salir ");
        jMenu3.add(btnSalir);

        btnCerrarSesion.setText("Cerrar sesión");
        jMenu3.add(btnCerrarSesion);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Gestión");

        btnAveria.setText("Avería");
        jMenu2.add(btnAveria);

        btnUsuario.setText("Usuario");
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(btnUsuario);

        btnMaquina.setText("Máquinas");
        jMenu2.add(btnMaquina);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(lblBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblBienvenida)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        // 1. Crear la vista
        UsuariosView viewUsuarios = new UsuariosView();

        // 2. Crear el DAO (ya lo tienes hecho)
        dao.UsuarioDAO daoUsuario = new dao.impl.UsuarioDAOImpl();

        // 3. Aquí deberíamos conectar un CONTROLADOR. 
        // Como paso rápido (si no vas a crear la clase UsuariosController aparte), 
        // puedes cargar la lista directamente aquí:

        viewUsuarios.llenarTabla(daoUsuario.listar());

        // HACER VISIBLE LA VENTANA
        viewUsuarios.setVisible(true);

    }//GEN-LAST:event_btnUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaAdmin().setVisible(true));
    }
    
    // Métodos puente para los items del menú de Gestión
    public void esMenuUsuarios(java.awt.event.ActionListener l){
        btnUsuario.addActionListener(l);
    }
    
    public void esMenuAverias(java.awt.event.ActionListener l){
        btnAveria.addActionListener(l);
    }
    
    public void esMenuMaquinas(java.awt.event.ActionListener l){
        btnMaquina.addActionListener(l);
    } 
    
    private void personalizarVista(){
        Util.EstiloUI.aplicarVentana(this);
        
        Util.EstiloUI.aplicarMenuBar(jMenuBar1);
        Util.EstiloUI.aplicarMenu(jMenu3);
        Util.EstiloUI.aplicarMenu(jMenu2);
        
        Util.EstiloUI.aplicarTituloDashboard(lblBienvenida);
        
        Util.EstiloUI.aplicarMenuItem(btnAveria);
        Util.EstiloUI.aplicarMenuItem(btnUsuario);
        Util.EstiloUI.aplicarMenuItem(btnMaquina);
        Util.EstiloUI.aplicarMenuItem(btnPerfil);
        Util.EstiloUI.aplicarMenuItem(btnSalir);
       
        Util.EstiloUI.aplicarBotonCerrarSesion(btnCerrarSesion);
        
    }
    
    // Método para mostrar el nombre del usuario que inicie sesión
    public void mostrarUsuario(String nombre) {
        lblBienvenida.setText("Bienvenido, " + nombre);
    } 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAveria;
    private javax.swing.JMenuItem btnCerrarSesion;
    private javax.swing.JMenuItem btnMaquina;
    private javax.swing.JMenuItem btnPerfil;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JMenuItem btnUsuario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblBienvenida;
    // End of variables declaration//GEN-END:variables
}
