/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.AgregarMaquina;
import controlador.MaquinaControlador;
import dao.AveriaDAO;
import dao.MaquinariaDAO;
import dao.UsuarioDAO;
import dao.impl.MaquinariaDAOImpl;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modelo.Usuario;

/**
 *
 * @author konatasht
 */
public class VistaMaquinas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaMaquinas.class.getName());

    /**
     * Creates new form VistaMaquinas
     */
    public VistaMaquinas() {
        initComponents();
        setTitle("Gestión de Máquinas");
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        ((javax.swing.JComponent) getContentPane()).setBorder(
        javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        personalizarVista();
        
        getContentPane().removeAll(); // limpiar layout de NetBeans

        setLayout(new java.awt.BorderLayout());
        javax.swing.JPanel panelBotones = new javax.swing.JPanel();
        panelBotones.setLayout(new java.awt.GridLayout(6, 1, 10, 10));

        panelBotones.add(btnAgregar);
        panelBotones.add(btnEditar);
        panelBotones.add(btnEliminar);
        panelBotones.add(btnRefrescarLista);
        panelBotones.add(btnMaquinaria);
        panelBotones.add(btnEstados);
        
        add(panelBotones, java.awt.BorderLayout.WEST);
        add(jScrollPane1, java.awt.BorderLayout.CENTER);
        add(btnVolver, java.awt.BorderLayout.SOUTH);
        revalidate();
        repaint();
           jTable1.setModel(new javax.swing.table.DefaultTableModel(
    new Object [][] {},
    new String [] {
        "Nombre", "Cód. Maq", "Estado", "Descripción"
    }
) {
    @Override
    public boolean isCellEditable(int row, int column) {
        return false;
    }
});
        
        TableRowSorter<DefaultTableModel> sorter = 
        new TableRowSorter<>((DefaultTableModel) jTable1.getModel());

        jTable1.setRowSorter(sorter);
        sorter.setComparator(1, new java.util.Comparator<Integer>() {
            public int compare(Integer a, Integer b) {
                return a.compareTo(b);
            }
        });

        sorter.setComparator(2, new java.util.Comparator<Integer>() {
            public int compare(Integer a, Integer b) {
                return a.compareTo(b);
            }
        });
        
     
        
        // Después de la línea donde se crean los botones, agrega:

    

    btnMaquinaria.addActionListener(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnMaquinariaActionPerformed(evt);
        }
    });

    btnEstados.addActionListener(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnEstadosActionPerformed(evt);
        }
    });

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRefrescarLista = new javax.swing.JButton();
        btnMaquinaria = new javax.swing.JButton();
        btnEstados = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAgregar.setText("Agregar Máquina");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnRefrescarLista.setText("Refrescar Lista");
        btnRefrescarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarListaActionPerformed(evt);
            }
        });

        btnMaquinaria.setText("Tipo Maquina");
        btnMaquinaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaquinariaActionPerformed(evt);
            }
        });

        btnEstados.setText("Tipo Estados");
        btnEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadosActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Cód. Maq", "Estado", "Descripción"
            }
        ));
        jTable1.setFocusable(false);
        jScrollPane1.setViewportView(jTable1);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVolver)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRefrescarLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMaquinaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEstados)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefrescarLista)
                        .addGap(20, 20, 20)
                        .addComponent(btnMaquinaria)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
   
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
       
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
           
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnMaquinariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaquinariaActionPerformed

    }//GEN-LAST:event_btnMaquinariaActionPerformed

    private void btnEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadosActionPerformed
       
   
    }//GEN-LAST:event_btnEstadosActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
     
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRefrescarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarListaActionPerformed
        
    }//GEN-LAST:event_btnRefrescarListaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    java.awt.EventQueue.invokeLater(() -> {
        VistaMaquinas vista = new VistaMaquinas();
        MaquinariaDAO dao = new MaquinariaDAOImpl();
        Usuario usuarioActual = new Usuario();
        
        new MaquinaControlador(vista, usuarioActual);

        vista.setVisible(true);
    });
}
    
    
    
    public void setBtnAgregarListener(java.awt.event.ActionListener listener) {
        btnAgregar.addActionListener(listener);
    }

    public void setBtnEditarListener(java.awt.event.ActionListener listener) {
        btnEditar.addActionListener(listener);
    }

    public void setBtnEliminarListener(java.awt.event.ActionListener listener) {
        btnEliminar.addActionListener(listener);
    }
    
    public void setBtnRefrescarListaListener(java.awt.event.ActionListener listener) {
        btnRefrescarLista.addActionListener(listener);
    }
    
    public void setBtnVolverListener(java.awt.event.ActionListener listener) {
        btnVolver.addActionListener(listener);
    }
    
    // Método para obtener columna seleccionada
    public int getIdSeleccionado() {
        int fila = jTable1.getSelectedRow();
        if (fila == -1) return -1;

        Object valor = jTable1.getValueAt(fila, 1);
        return Integer.parseInt(valor.toString());
    }
    
    // Método para mostrar mensaje éxitoso
    public void mostrarMensaje(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Información", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }

    // Método para mostrar un mensaje error
    public void mostrarError(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    
    // Método para llenar la tabla
    public void llenarTabla(java.util.List<modelo.Maquinaria> lista) {

    javax.swing.table.DefaultTableModel modelo =
        (javax.swing.table.DefaultTableModel) jTable1.getModel();

    modelo.setRowCount(0);
    for (modelo.Maquinaria m : lista) {
        modelo.addRow(new Object[]{
            m.getNombre(),
            m.getCodigoMaquinaria(),
            m.getCodigoEstadoFK(),
            m.getTipoMaquinariaFK()
        });
    }
}
    
    // Método para personalizar la clase
    private void personalizarVista(){
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        Util.EstiloUI.aplicarVentana(this);
        Util.EstiloUI.aplicarBotonPrimario(btnEditar);
        Util.EstiloUI.aplicarBotonPrimario(btnAgregar);
        Util.EstiloUI.aplicarBotonPeligro(btnEliminar);
        Util.EstiloUI.aplicarBotonPrimario(btnMaquinaria);
        Util.EstiloUI.aplicarBotonPrimario(btnEstados);
        Util.EstiloUI.aplicarBotonPrimario(btnRefrescarLista);
        Util.EstiloUI.aplicarTabla(jTable1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEstados;
    private javax.swing.JButton btnMaquinaria;
    private javax.swing.JButton btnRefrescarLista;
    private javax.swing.JButton btnVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
